const TYPES = {
  POST_LOADING: 'POST_LOADING',
  GET_ALL_LOCAL_POSTS: 'GET_ALL_LOCAL_POSTS',
  GET_ALL_POST: 'GET_ALL_POST',
  GET_ONE_POST: 'GET_ONE_POST',
  ERROR: 'ERROR',
  LOGOUT: 'LOGOUT',
};

export default TYPES;